# Generated by Django 6.0.2 on 2026-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('One-time', 'One-time')], max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
